version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: todo-backend
        volumes:
            - .:/var/www
        environment:
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=todo_app
            - DB_USERNAME=root
            - DB_PASSWORD=root
        expose:
            - 9000

    web:
        image: nginx:latest
        container_name: todo_web
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    db:
        image: mysql:8.0
        container_name: todo_db
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: todo_app
        volumes:
            - dbdata:/var/lib/mysql

volumes:
    dbdata:
